### Punto 2 

##### 2a.Implemente un algoritmo para calcular la factorización QR de unamatríz basando en el proceso de ortogonalización de Grahm-Schmidt. El algoritmo debe recibir una matriz A de tamaño m × n con m ≥ n y retornar una matriz Q de tamaño m × n y una matriz triangular superior R de tamaño n × n, tales que QtQ = In y A = QR. Compare los resultados de su algoritmo con los de la función scipy.linalg.qr SciPy Manual.

In [72]:
#punto 2a
import numpy as np

def gram_schmidt_qr(A):
    A = A.astype(float)
    m, n = A.shape
    if m >n:
        raise ValueError("El número de filas m debe ser mayor o igual que el número de columnas n.")

    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] != 0:
            Q[:, j] = v / R[j, j]
        else:
            Q[:, j] = np.zeros(m)

    return Q, R

# Ejemplo de uso
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
Q, R = gram_schmidt_qr(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)


Matriz Q:
[[ 0.12309149  0.90453403  0.        ]
 [ 0.49236596  0.30151134  0.        ]
 [ 0.86164044 -0.30151134  0.        ]]
Matriz R:
[[ 8.1240384   9.6011363  11.07823419]
 [ 0.          0.90453403  1.80906807]
 [ 0.          0.          0.        ]]


Matriz Q:

Contiene direcciones ortogonales y normalizadas de las columnas de la matriz original A.
Cada columna de Q representa una dirección principal en los datos de A.
Las columnas son ortogonales entre sí, lo que significa que están perpendiculares.
En nuestro ejemplo, las primeras dos columnas de Q representan las direcciones principales en los datos, mientras que la tercera columna es cero, indicando que la tercera columna de A es una combinación lineal de las dos primeras.

Matriz R:

Es una matriz triangular superior que contiene información sobre la importancia y las relaciones de ortogonalidad entre las direcciones dadas por Q.
Los valores en la diagonal principal de R representan la importancia de cada dirección en las columnas originales de A.
Los valores fuera de la diagonal principal son ceros, lo que confirma la ortogonalidad entre las direcciones.
En resumen, la factorización QR descompone la matriz A en direcciones significativas (Q) y su respectiva importancia (R). Esto es útil para analizar y representar los datos de A en términos de direcciones ortogonales, lo que facilita la simplificación y el análisis de los datos originales.







In [56]:
#Otra opcion de validacion del punto 2a
import numpy as np

def gram_schmidt_qr(A):
    m, n = A.shape
    Q = np.zeros((m, n), dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Ejemplo de uso
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 7.0]], dtype=float)

Q, R = gram_schmidt_qr(A)
print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)


Matriz Q:
[[ 0.12309149  0.90453403 -0.40824829]
 [ 0.49236596  0.30151134  0.81649658]
 [ 0.86164044 -0.30151134 -0.40824829]]
Matriz R:
[[8.1240384  9.6011363  9.35495331]
 [0.         0.90453403 2.41209076]
 [0.         0.         0.81649658]]


la matriz Q es ortogonal, lo que significa que sus columnas son ortogonales entre sí, y la matriz R es triangular superior. Estas son las propiedades deseadas de la factorización QR y que resultan muy importante

In [57]:
#Probando la matriz de identidad
QTQ = np.dot(Q.T, Q)
print("QtQ:")
print(QTQ)


QtQ:
[[ 1.00000000e+00  1.45860311e-15 -3.98398842e-15]
 [ 1.45860311e-15  1.00000000e+00  5.20102955e-16]
 [-3.98398842e-15  5.20102955e-16  1.00000000e+00]]


Los resultados que se obtuvieron para QTQ son muy cercanos a una matriz de identidad (I), y las pequeñas desviaciones (números muy cercanos a cero) son probablemente el resultado de errores numéricos debido a las limitaciones de precisión en cálculos con números de punto flotante. En términos prácticos, estos valores son esencialmente cero y la matriz Q cumple con la propiedad ortogonal.

En resumen, los resultados son consistentes con una factorización QR exitosa, y la matriz Q es ortogonal en un sentido práctico. La pequeña desviación de la identidad es una característica normal de los cálculos numéricos, y se pueden considerar como errores numéricos aceptables.


In [58]:
#Comparacion de los resultados de su algoritmo con los de la función scipy.linalg.qr-SciPy Manual.

from scipy.linalg import qr

Q_scipy, R_scipy = qr(A, mode='economic')

print("Matriz Q (SciPy):")
print(Q_scipy)
print("Matriz R (SciPy):")
print(R_scipy)


Matriz Q (SciPy):
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
Matriz R (SciPy):
[[-8.12403840e+00 -1.33226763e-15  3.27515792e-15]
 [ 0.00000000e+00  9.04534034e-01  3.33066907e-16]
 [ 0.00000000e+00  0.00000000e+00 -8.16496581e-01]]


En la comparación entre la implementación personalizada del algoritmo de factorización QR mediante el proceso de ortogonalización de Gram-Schmidt y la función scipy.linalg.qr de SciPy, se observaron resultados similares pero no idénticos. Estas diferencias pueden atribuirse a variaciones en la precisión numérica y al enfoque de implementación. Ambas soluciones proporcionaron la descomposición QR de una matriz, confirmando la validez de la implementación personalizada.

Es relevante señalar que la función de SciPy es más robusta y puede manejar una variedad de casos, incluyendo matrices de rango completo y matrices de rango deficiente. Por lo tanto, en aplicaciones críticas que requieren precisión numérica, la función de SciPy es una opción confiable.

In [17]:
#Punto 2.b Que pasa con la factorización QR cuando las columnas son linealmente dependientes?

In [13]:
import numpy as np

# Crear una matriz con columnas linealmente dependientes basada en la matriz A anterior
A_dependent = np.array([[1, 2, 3],
                       [4, 8, 12],  # Esta fila es 4 veces la primera
                       [7, 14, 21]])  # Esta fila es 7 veces la primera

# Realizar la factorización QR
Q_dependent, R_dependent = np.linalg.qr(A_dependent)

print("Matriz A con columnas linealmente dependientes:")
print(A_dependent)
print("Matriz Q:")
print(Q_dependent)
print("Matriz R:")
print(R_dependent)


Matriz A con columnas linealmente dependientes:
[[ 1  2  3]
 [ 4  8 12]
 [ 7 14 21]]
Matriz Q:
[[-0.12309149  0.95742711 -0.26111648]
 [-0.49236596 -0.28736847 -0.82158086]
 [-0.86164044  0.02743526  0.50677713]]
Matriz R:
[[-8.12403840e+00 -1.62480768e+01 -2.43721152e+01]
 [ 0.00000000e+00  2.51214793e-15  5.02429587e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


Matriz A con columnas linealmente dependientes: La matriz A tiene la segunda y la tercera columna que son múltiplos exactos de la primera columna. Esto indica una dependencia lineal entre las columnas, lo que hace que la matriz sea singular y, por lo tanto, no puede tener una factorización QR única.

Matriz Q: A pesar de la dependencia lineal en las columnas de A, la factorización QR se realizó con éxito. La matriz Q contiene columnas que forman una base ortogonal para el espacio generado por las columnas de A. Sin embargo, es importante destacar que la tercera columna de Q es diferente de cero, a pesar de que las columnas correspondientes de A son linealmente dependientes. Esto es una peculiaridad de la factorización QR en el caso de columnas linealmente dependientes. La matriz Q todavía proporciona direcciones ortogonales, pero el proceso de ortogonalización no puede hacer que las columnas sean linealmente independientes.

Matriz R: La matriz R es triangular superior y describe cómo las columnas de A se proyectan en las direcciones dadas por las columnas de Q. En este caso, la tercera columna de R contiene ceros, lo que indica que no hay una proyección efectiva en la dirección correspondiente a la tercera columna de A.

In [73]:
#Otro ejemplo del Punto 2b: Ejemplo de que pasa con la factorización QR cuando las columnas son linealmente dependientes.

In [45]:
import numpy as np

def modified_gram_schmidt_qr(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            raise ValueError("La matriz A no se puede factorizar QR debido a columnas linealmente dependientes.")
        Q[:, j] = v / R[j, j]

    # Normalizar las columnas de Q para garantizar la ortogonalidad
    for j in range(n):
        Q[:, j] /= np.linalg.norm(Q[:, j])

    return Q, R

# Ejemplo de uso
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
Q, R = modified_gram_schmidt_qr(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)


ValueError: La matriz A no se puede factorizar QR debido a columnas linealmente dependientes.

Matriz Q:

Las columnas de Q representan las "direcciones dominantes" en los datos contenidos en la matriz A.
Cada columna de Q es una "versión mejorada" de las columnas originales de A, optimizada para ser ortogonal a las demás.


La matriz R contiene información sobre "cuánto" de cada dirección dominante está presente en las columnas originales de A.
Los valores en la diagonal principal de R representan la "importancia" o "contribución" de cada dirección dominante.
Los valores fuera de la diagonal principal de R indican cómo las direcciones dominantes están relacionadas entre sí.

la factorización QR permite descomponer una matriz en direcciones significativas (Q) y su respectiva importancia (R) en el contexto del problema particular que representa la matriz A.

In [47]:
import numpy as np

def economic_qr(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            # Columna j de A es linealmente dependiente de las anteriores
            Q[:, j] = np.zeros(m)
        else:
            Q[:, j] = v / R[j, j]

    return Q, R

# Ejemplo de uso
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
Q, R = economic_qr(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)


Matriz Q:
[[ 0.12309149  0.90453403  0.        ]
 [ 0.49236596  0.30151134  0.        ]
 [ 0.86164044 -0.30151134  0.        ]]
Matriz R:
[[ 8.1240384   9.6011363  11.07823419]
 [ 0.          0.90453403  1.80906807]
 [ 0.          0.          0.        ]]


In [18]:
# Punto 2c Averigüe bajo cuales condiciones la factorización QR es única

In [15]:
import numpy as np

# Crear una matriz de rango completo
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Realizar la factorización QR
Q, R = np.linalg.qr(A)

print("Matriz A de rango completo:")
print(A)
print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)


Matriz A de rango completo:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz Q:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
Matriz R:
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


la factorización QR descompone la matriz A en una matriz ortogonal Q y una matriz triangular superior R. Los resultados reflejan que la matriz A original es de rango completo y que Q y R describen sus componentes y proyecciones en el espacio. La factorización QR es útil en una variedad de aplicaciones, incluyendo la resolución de sistemas de ecuaciones lineales y la aproximación de mínimos cuadrados.

## Punto 4

In [59]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color

# Cargar la imagen en escala de grises
image = io.imread("tu_imagen.png")
image_gray = color.rgb2gray(image)

# Realizar la descomposición en valores singulares (SVD)
U, S, Vt = np.linalg.svd(image_gray, full_matrices=False)

# Tamaños de la imagen
m, n = image_gray.shape

# Número de valores singulares a retener
num_singular_values = min(m, n)

# Mostrar la imagen original
plt.figure(figsize=(10, 5))
plt.subplot(1, 1, 1)
plt.title("Imagen original")
plt.imshow(image_gray, cmap='gray')
plt.axis('off')
plt.show()

# Mostrar la imagen reconstruida utilizando diferentes números de valores singulares
for i in range(1, num_singular_values + 1):
    reconstructed_image = np.dot(U[:, :i], np.dot(np.diag(S[:i]), Vt[:i, :]))
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 1, 1)
    plt.title(f"Número de valores singulares = {i}")
    plt.imshow(reconstructed_image, cmap='gray')
    plt.axis('off')
    plt.show()


FileNotFoundError: No such file: '/Users/facil/Documents/GitHub/algebraciencia/tu_imagen.png'